services:
    database:
        container_name: ecommerce
        hostname: ecommerce_database
        image: mysql:latest
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: ecommerce
        ports:
            - '3306:3306'
        volumes:
            - ~/ecommerce:/var/lib/mysql
